helth_project/api/urls.py
from django.urls import path

from .views import PostViewSet


app_name = 'api'

urlpatterns = [
    path('v1/posts/', PostViewSet.as_view({'get': 'list'})),
    path('v1/posts/<int:pk>/', PostViewSet.as_view({'put': 'update'})),
    path('v1/posts/create/', PostViewSet.as_view({'post': 'create'})),
]

helth_project/helth_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls', namespace='api')),
]

handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

helth_project/posts/urls.py
from django.urls import path

from .views import (PostListView,
                    GroupListView,
                    ProfileListView,
                    PostDetailView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView)


app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='index_list'),
    path('group/<slug:slug>/', GroupListView.as_view(), name='group_list'),
    path('profile/<str:username>/', ProfileListView.as_view(), name='profile'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/edit/', PostUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete')
]

helth_project/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from .constants import MAX_LENGTH

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=MAX_LENGTH)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Группы'
        verbose_name = 'Группа'


class Post(models.Model):
    text = models.TextField(verbose_name='Текст', help_text='Текст поста')
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группы',
        help_text='Группа, к которой будет относиться пост'
    )

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return f'/post/{self.pk}'

    class Meta:
        verbose_name_plural = 'Публикации'
        verbose_name = 'Публикация'
        ordering = ['-pub_date']

helth_project/posts/forms.py
from django.forms import ModelForm, ValidationError

from .views import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

    def clean_text(self):
        data = self.cleaned_data['text']
        if data == '':
            raise ValidationError('А кто поле будет заполнять, Пушкин?')
        return data

helth_project/posts/views.py
from django.views.generic import (ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Group, Post
from .forms import PostForm
from .constants import PAGE_COUNT


class PostListView(ListView):
    template_name = 'posts/index.html'
    context_object_name = 'posts'
    paginate_by = PAGE_COUNT

    def get_queryset(self):
        return Post.objects.all().select_related('author').select_related('group')


class GroupListView(ListView):
    template_name = 'posts/group_list.html'
    context_object_name = 'posts'
    paginate_by = PAGE_COUNT

    def get_queryset(self):
        return Post.objects.filter(
            group__slug=self.kwargs['slug']
        ).select_related('group').select_related('author')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['group'] = Group.objects.get(slug=self.kwargs['slug'])
        return context


class ProfileListView(ListView):
    template_name = 'posts/profile.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(
            author__username=self.kwargs['username']
        ).select_related('author').select_related('group')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = Post.objects.filter(author__username=self.kwargs['username'])
        context['posts_count'] = Post.objects.filter(author__username=self.kwargs['username']).count()
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    pk_url_kwarg = 'pk'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['text', 'group', 'author']
    template_name = 'posts/post_create.html'


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'posts/post_create.html'
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = True
        return context


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/post_delete.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = Post.objects.get(pk=self.kwargs['pk'])
        return context

helth_project/posts/templates/posts/group_list.html
{% extends 'layout/base.html' %}
{% block title %}Запись сообщества {{ group }}{% endblock %}
{% block content %}
  <div class="container py-5">
    {% block head%}
    <h1>Группа: {{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    {% endblock %}
    <article>
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.username }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        <p><a href="{% url 'posts:post_detail' post.pk %}">подробнее о посте</a></p>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </article>
  </div>
{% endblock %}

helth_project/posts/templates/posts/index.html
{% extends 'layout/base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content%}
  <div class="container py-5">
    <article>
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.username }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        <p><a href="{% url 'posts:post_detail' post.pk %}">подробнее о посте</a></p>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </article>
  </div>
{% endblock %}

helth_project/posts/templates/posts/post_create.html
{% extends 'layout/base.html' %}
{% block title %}
  {% if is_edit %}
    Добавить запись
  {% else %}
    Редактировать запись
  {% endif %}
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
          Редактировать пост
          {% else %}
          Новый пост 
          {% endif %}            
        </div>
        <div class="card-body">
        {% load user_filters %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors%}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors%}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <form method="post" action="">
          {% csrf_token %}
            {% for field in form %}         
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              {{ field|addclass:'form-control' }} 
                {% if field.help_text %}
                  <small 
                    id="{{ field.id_for_label }}-help"
                      class="form-text text-muted"
                >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}                  
            </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                Сохранить
                {% else %}
                Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

helth_project/posts/templates/posts/post_delete.html
{% extends 'layout/base.html' %}
{% block title %}Удаление поста{% endblock %}
{% block content%}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-5 p-5">
      <div class="card">
        <div class="card-header">
          Удаление поста "{{ post }}"
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">Удалить пост</button>
          </form>
          <div>
            <a href="{% url 'posts:post_detail' post.pk %}">Вернуться к посту</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

helth_project/posts/templates/posts/post_detail.html
{% extends 'layout/base.html' %}
{% block title %}{{ post.text|truncatechars:30 }}{% endblock %}
{% block content%}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }} 
      </li>
      {% if post.group %}  
        <li class="list-group-item">
          Группа: {{ post.group.title }}
          <p>
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи этой группы</a>
          </a>
          </p>
        </li>
      {% endif %}
      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя
        </a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:post_edit' post.pk %}">
          редактировать пост
        </a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:post_delete' post.pk %}">
          удалить пост
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>
     {{ post.text }}
    </p>
  </article>
</div>
{% endblock %}

helth_project/posts/templates/posts/profile.html
{% extends 'layout/base.html' %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content%}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.get_full_name}}</h1>
    <h3>Всего постов: {{ posts_count }}</h3>
    <article>
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        </article>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы: {{ post.group.slug }}</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}      
      {% endfor %}
  </div>
{% endblock %}