helth_project/api/urls.py
from django.urls import path

from .views import PostViewSet


app_name = 'api'

urlpatterns = [
    path('v1/posts/', PostViewSet.as_view({'get': 'list'})),
    path('v1/posts/<int:pk>/', PostViewSet.as_view({'put': 'update'})),
    path('v1/posts/create/', PostViewSet.as_view({'post': 'create'})),
]

helth_project/helth_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls', namespace='api')),
]

handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

helth_project/posts/urls.py
from django.urls import path

from .views import (PostListView,
                    GroupListView,
                    ProfileListView,
                    PostDetailView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView)


app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='index_list'),
    path('group/<slug:slug>/', GroupListView.as_view(), name='group_list'),
    path('profile/<str:username>/', ProfileListView.as_view(), name='profile'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/edit/', PostUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete')
]

helth_project/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from .constants import MAX_LENGTH

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=MAX_LENGTH)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Группы'
        verbose_name = 'Группа'


class Post(models.Model):
    text = models.TextField(verbose_name='Текст', help_text='Текст поста')
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группы',
        help_text='Группа, к которой будет относиться пост'
    )

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return f'/post/{self.pk}'

    class Meta:
        verbose_name_plural = 'Публикации'
        verbose_name = 'Публикация'
        ordering = ['-pub_date']

helth_project/posts/forms.py
from django.forms import ModelForm, ValidationError

from .views import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

    def clean_text(self):
        data = self.cleaned_data['text']
        if data == '':
            raise ValidationError('А кто поле будет заполнять, Пушкин?')
        return data

helth_project/posts/views.py
from django.views.generic import (ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Group, Post
from .forms import PostForm
from .constants import PAGE_COUNT


class PostListView(ListView):
    template_name = 'posts/index.html'
    context_object_name = 'posts'
    paginate_by = PAGE_COUNT

    def get_queryset(self):
        return Post.objects.all().select_related('author').select_related('group')


class GroupListView(ListView):
    template_name = 'posts/group_list.html'
    context_object_name = 'posts'
    paginate_by = PAGE_COUNT

    def get_queryset(self):
        return Post.objects.filter(
            group__slug=self.kwargs['slug']
        ).select_related('group').select_related('author')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['group'] = Group.objects.get(slug=self.kwargs['slug'])
        return context


class ProfileListView(ListView):
    template_name = 'posts/profile.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(
            author__username=self.kwargs['username']
        ).select_related('author').select_related('group')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = Post.objects.filter(author__username=self.kwargs['username'])
        context['posts_count'] = Post.objects.filter(author__username=self.kwargs['username']).count()
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    pk_url_kwarg = 'pk'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['text', 'group', 'author']
    template_name = 'posts/post_create.html'


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'posts/post_create.html'
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = True
        return context


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/post_delete.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = Post.objects.get(pk=self.kwargs['pk'])
        return context

helth_project/posts/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© 2025 Copyright <span style="color:red">Helthy</span>Life</p>
</footer>

helth_project/posts/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index_list' %}">
        <img src="{% static 'posts/img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Helthy</span>Life
      </a>

      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
          href="{% url 'about:author' %}"
          >
          Об авторе
        </a>
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
             href="{% url 'about:tech' %}"
          >
            Технологии
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
             href="{% url 'posts:post_create' %}"
          >
            Новая запись
          </a>
        </li> 
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'users:password_change' %}active{% endif %}" 
             href="{% url 'users:password_change' %}"
          >
            Изменить пароль
          </a>
        </li> 
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}" 
             href="{% url 'users:logout' %}"
          >
            Выйти
          </a>
        </li> 
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" 
             href="{% url 'users:login' %}"
          >
            Войти
          </a>
        </li> 
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" 
             href="{% url 'users:signup' %}"
          >
            Регистрация
          </a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>      
</header>

helth_project/posts/templates/includes/paginator.html
{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}